import type { ClinicalTrial } from "./types.js";

export const trials: ClinicalTrial[] = [
  {
    id: "NCT-001",
    name: "AURORA-1: Pocenbrodib in mCRPC",
    sponsor: "Pathos Therapeutics",
    phase: "II",
    status: "recruiting",
    indication: "Metastatic castration-resistant prostate cancer",
    primaryEndpoint: "Radiographic progression-free survival at 12 months",
    enrollment: 180,
    startDate: "2023-03-15",
    estimatedCompletionDate: "2025-09-01",
    adverseEventRate: 31.2,
    responseRate: 38.5,
    keyFindings: [
      "Interim analysis at 6 months shows 38.5% PSA50 response rate",
      "Grade 3+ adverse events in 31.2% of patients, primarily fatigue and nausea",
      "No dose-limiting toxicities at the 400mg BID dose level",
    ],
  },
  {
    id: "NCT-002",
    name: "BEACON-3: Vemurafenib + Cobimetinib in Melanoma",
    sponsor: "Genentech",
    phase: "III",
    status: "completed",
    indication: "BRAF V600E-mutant unresectable melanoma",
    primaryEndpoint: "Overall survival",
    enrollment: 495,
    startDate: "2020-06-01",
    estimatedCompletionDate: "2024-01-15",
    adverseEventRate: 58.4,
    responseRate: 61.3,
    keyFindings: [
      "Median OS of 22.5 months vs 17.4 months for vemurafenib monotherapy",
      "ORR of 61.3% vs 45.0% for combination vs monotherapy",
      "Photosensitivity in 41% of patients required dose modification",
    ],
  },
  {
    id: "NCT-003",
    name: "CLARITY-1: Novel BET Inhibitor FT-9001 Phase I Dose Escalation",
    sponsor: "Pathos Therapeutics",
    phase: "I",
    status: "recruiting",
    indication: "Advanced solid tumors with MYC amplification",
    primaryEndpoint: "Maximum tolerated dose and recommended Phase II dose",
    enrollment: 45,
    startDate: "2024-01-10",
    estimatedCompletionDate: "2025-12-31",
    adverseEventRate: 22.0,
    responseRate: null,
    keyFindings: [
      "Three dose cohorts completed (50mg, 100mg, 200mg QD)",
      "No DLTs observed at any dose level to date",
      "Preliminary PK data shows dose-proportional exposure",
    ],
  },
  {
    id: "NCT-004",
    name: "SUMMIT: Neratinib in HER2-mutant Solid Tumors",
    sponsor: "Puma Biotechnology",
    phase: "II",
    status: "completed",
    indication: "HER2-mutant non-breast solid tumors",
    primaryEndpoint: "Objective response rate",
    enrollment: 141,
    startDate: "2018-11-01",
    estimatedCompletionDate: "2022-05-20",
    adverseEventRate: 44.7,
    responseRate: 28.0,
    keyFindings: [
      "28% ORR across all tumor types with HER2 mutations",
      "Highest ORR in biliary tract (34%) and cervical (29%) cancers",
      "Diarrhea management protocol reduced grade 3+ events from 33% to 7%",
    ],
  },
  {
    id: "NCT-005",
    name: "RADIANT-4: Everolimus in Nonfunctional NET",
    sponsor: "Novartis",
    phase: "III",
    status: "completed",
    indication: "Progressive, nonfunctional neuroendocrine tumors",
    primaryEndpoint: "Progression-free survival",
    enrollment: 302,
    startDate: "2012-03-01",
    estimatedCompletionDate: "2016-08-15",
    adverseEventRate: 52.3,
    responseRate: 2.0,
    keyFindings: [
      "Median PFS 11.0 months vs 3.9 months placebo (HR 0.48)",
      "Benefit seen regardless of tumor origin (lung, GI, unknown primary)",
      "Stomatitis and infections were the most common grade 3/4 AEs",
    ],
  },
  {
    id: "NCT-006",
    name: "KEYNOTE-522: Pembrolizumab in Early TNBC",
    sponsor: "Merck",
    phase: "III",
    status: "completed",
    indication: "Early-stage triple-negative breast cancer",
    primaryEndpoint: "Pathologic complete response and event-free survival",
    enrollment: 1174,
    startDate: "2017-02-27",
    estimatedCompletionDate: "2023-03-10",
    adverseEventRate: 76.8,
    responseRate: 64.8,
    keyFindings: [
      "pCR rate 64.8% pembrolizumab + chemo vs 51.2% placebo + chemo",
      "EFS HR 0.63, representing 37% reduction in risk of events",
      "Immune-mediated AEs in 34.1%, including thyroid dysfunction and adrenal insufficiency",
    ],
  },
  {
    id: "NCT-007",
    name: "FT-7051-001: Pocenbrodib Phase I in CRPC",
    sponsor: "Pathos Therapeutics",
    phase: "I",
    status: "completed",
    indication: "Castration-resistant prostate cancer",
    primaryEndpoint: "Safety, tolerability, and RP2D determination",
    enrollment: 68,
    startDate: "2021-05-01",
    estimatedCompletionDate: "2023-07-30",
    adverseEventRate: 28.5,
    responseRate: 29.4,
    keyFindings: [
      "RP2D established at 400mg BID",
      "PSA50 response in 29.4% of evaluable patients",
      "Favorable safety profile; no cardiac toxicity signals observed",
    ],
  },
  {
    id: "NCT-008",
    name: "TOPAZ-1: Durvalumab in Biliary Tract Cancer",
    sponsor: "AstraZeneca",
    phase: "III",
    status: "completed",
    indication: "Advanced biliary tract cancer",
    primaryEndpoint: "Overall survival",
    enrollment: 685,
    startDate: "2018-07-02",
    estimatedCompletionDate: "2023-01-14",
    adverseEventRate: 62.7,
    responseRate: 26.7,
    keyFindings: [
      "Median OS 12.8 months durvalumab + GemCis vs 11.5 months GemCis alone (HR 0.80)",
      "ORR 26.7% vs 18.7%, DCR 84.3% vs 77.3%",
      "Benefit maintained across BTC subtypes and PD-L1 expression levels",
    ],
  },
];
